name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: branch-name

extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    failOnThreshold: moderate  # Optional: moderate (default), low, high, critical
    variableGroupName: ffc-doc-statement-generator-env-var
    pr_params:
      container.pollWindowEnabled: $(pr_pollWindowEnabled)
      container.pollWindowStart: $(pr_pollWindowStart)
      container.pollWindowEnd: $(pr_pollWindowEnd)
      container.pollWindowDays: $(pr_pollWindowDays)
      container.sfi23QuarterlyStatementEnabled: $(pr_sfi23QuarterlyStatementEnabled)
      container.showSfi23PaymentPeriod: $(pr_showSfi23PaymentPeriod)
      container.delinkedPaymentStatementEnabled: $(pr_delinkedPaymentStatementEnabled)
      container.publishingFrequency: $(pr_publishingFrequency)
      container.sendCrmMessageEnabled: $(pr_sendCrmMessageEnabled)
    snd2_params:
      container.pollWindowEnabled: $(snd2_pollWindowEnabled)
      container.pollWindowStart: $(snd2_pollWindowStart)
      container.pollWindowEnd: $(snd2_pollWindowEnd)
      container.pollWindowDays: $(snd2_pollWindowDays)
      container.sfi23QuarterlyStatementEnabled: $(snd2_sfi23QuarterlyStatementEnabled)
      container.showSfi23PaymentPeriod: $(snd2_showSfi23PaymentPeriod)
      container.delinkedPaymentStatementEnabled: $(snd2_delinkedPaymentStatementEnabled)
      container.publishingFrequency: $(snd2_publishingFrequency)
      container.sendCrmMessageEnabled: $(snd2_sendCrmMessageEnabled)
    dev_params:
      container.pollWindowEnabled: $(dev_pollWindowEnabled)
      container.pollWindowStart: $(dev_pollWindowStart)
      container.pollWindowEnd: $(dev_pollWindowEnd)
      container.pollWindowDays: $(dev_pollWindowDays)
      container.sfi23QuarterlyStatementEnabled: $(dev_sfi23QuarterlyStatementEnabled)
      container.showSfi23PaymentPeriod: $(dev_showSfi23PaymentPeriod)
      container.delinkedPaymentStatementEnabled: $(dev_delinkedPaymentStatementEnabled)
      container.publishingFrequency: $(dev_publishingFrequency)
      container.sendCrmMessageEnabled: $(dev_sendCrmMessageEnabled)
    test_params:
      container.pollWindowEnabled: $(test_pollWindowEnabled)
      container.pollWindowStart: $(test_pollWindowStart)
      container.pollWindowEnd: $(test_pollWindowEnd)
      container.pollWindowDays: $(test_pollWindowDays)
      container.sfi23QuarterlyStatementEnabled: $(test_sfi23QuarterlyStatementEnabled)
      container.showSfi23PaymentPeriod: $(test_showSfi23PaymentPeriod)
      container.delinkedPaymentStatementEnabled: $(test_delinkedPaymentStatementEnabled)
      container.publishingFrequency: $(test_publishingFrequency)
      container.sendCrmMessageEnabled: $(test_sendCrmMessageEnabled)
    pre_params:
      container.pollWindowEnabled: $(pre_pollWindowEnabled)
      container.pollWindowStart: $(pre_pollWindowStart)
      container.pollWindowEnd: $(pre_pollWindowEnd)
      container.pollWindowDays: $(pre_pollWindowDays)
      container.sfi23QuarterlyStatementEnabled: $(pre_sfi23QuarterlyStatementEnabled)
      container.showSfi23PaymentPeriod: $(pre_showSfi23PaymentPeriod)
      container.delinkedPaymentStatementEnabled: $(pre_delinkedPaymentStatementEnabled)
      container.publishingFrequency: $(pre_publishingFrequency)
      container.sendCrmMessageEnabled: $(pre_sendCrmMessageEnabled)
    prd_params:
      container.pollWindowEnabled: $(prd_pollWindowEnabled)
      container.pollWindowStart: $(prd_pollWindowStart)
      container.pollWindowEnd: $(prd_pollWindowEnd)
      container.pollWindowDays: $(prd_pollWindowDays)
      container.sfi23QuarterlyStatementEnabled: $(prd_sfi23QuarterlyStatementEnabled)
      container.showSfi23PaymentPeriod: $(prd_showSfi23PaymentPeriod)
      container.delinkedPaymentStatementEnabled: $(prd_delinkedPaymentStatementEnabled)
      container.publishingFrequency: $(prd_publishingFrequency)
      container.sendCrmMessageEnabled: $(prd_sendCrmMessageEnabled)
