services:
  ffc-doc-statement-generator:
    build:
      context: .
      target: production
    image: ffc-doc-statement-generator
    container_name: ffc-doc-statement-generator
    depends_on:
      - ffc-doc-statement-azurite
      - ffc-doc-statement-generator-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-doc-statement-generator-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      STATEMENT_TOPIC_ADDRESS: ${STATEMENT_TOPIC_ADDRESS:-ffc-doc-statements}${MESSAGE_QUEUE_SUFFIX}
      STATEMENT_SUBSCRIPTION_ADDRESS: ${STATEMENT_SUBSCRIPTION_ADDRESS:-ffc-doc-statement-generator}${MESSAGE_QUEUE_SUFFIX}
      PUBLISH_TOPIC_ADDRESS: ${PUBLISH_TOPIC_ADDRESS:-ffc-doc-statement-publish}${MESSAGE_QUEUE_SUFFIX}
      CRM_TOPIC_ADDRESS: ${CRM_TOPIC_ADDRESS:-ffc-doc-statement-crm}${MESSAGE_QUEUE_SUFFIX}
      POSTGRES_DB: ffc_doc_statement_generator
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-doc-statement-generator-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-devstoreaccount1}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      STATEMENT_RECEIVER_API_VERSION: v1
      STATEMENT_RECEIVER_ENDPOINT: http://localhost:3022
      SCHEDULES_ARE_PUBLISHED: "false"
      SFI23QUARTERLYSTATEMENT_ENABLED: ${SFI23QUARTERLYSTATEMENT_ENABLED:-false}
      SCHEDULE_ENABLED: ${SCHEDULE_ENABLED:-false}
      SEND_CRM_MESSAGE_ENABLED: ${SEND_CRM_MESSAGE_ENABLED:-false}
      SHOW_SFI_23_PAYMENT_PERIOD: "false"
      SEND_DELINKED_2024_STATEMENTS: ${SEND_DELINKED_2024_STATEMENTS:-false}
      PUBLISHING_FREQUENCY: ${PUBLISHING_FREQUENCY:-60000}
      ALERT_TOPIC_ADDRESS: ${ALERT_TOPIC_ADDRESS:-ffc-doc-alerting}${MESSAGE_QUEUE_SUFFIX}

  ffc-doc-statement-generator-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_doc_statement_generator
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres

  ffc-doc-statement-azurite:
    image: mcr.microsoft.com/azure-storage/azurite:3.32.0
    command: "azurite-blob --loose --blobHost 0.0.0.0"
    labels:
      com.docker.compose.pay.role: ffc-doc-statement-azurite
