environment: development
environmentCode:
name: ffc-doc-statement-generator
namespace: ffc-doc
workstream: ffc-doc
image: ffc-doc-statement-generator

labels: {}

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-doc-statement-generator-config-map

containerSecret:
  name: ffc-doc-statement-generator-container-secret
  type: Opaque

deployment:
  minReplicas: 1
  maxReplicas: 4
  cpuThreshold: 80
  memoryThreshold: 80

container:
  requestMemory: 150Mi
  requestCpu: 120m
  limitMemory: 150Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  statementTopicAddress: ffc-doc-statements
  statementSubscriptionAddress: ffc-doc-statement-generator
  publishTopicAddress: ffc-doc-statement-publish
  crmTopicAddress: ffc-doc-statement-crm
  azureStorageAccountName: ffcdoc
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  azureStorageCreateContainers: false
  storageContainer: statements
  storageFolder: outbound
  statementReceiverApiVersion: v1
  statementReceiverEndpoint: https://ffc-doc-statement-receiver
  schedulesArePublished: false
  showSfi23PaymentPeriod: false
  emailAddress: dummy
  apiKey: dummy
  emailTemplateKey: dummy
  sfi23QuarterlyStatementEnabled: false
  delinkedPaymentStatementEnabled: false
  scheduleEnabled: false
  sendCrmMessageEnabled: false
  saveLogEnabled: false
  sendDelinked2024Statements: false
  publishingFrequency: 1000

ingress:
  server: example.com

postgresService:
  postgresDb: ffc_doc_statement_generator
  postgresqlHost: ffc-doc-statement-generator-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

workloadIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
